version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: ecommerce_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ecommerce?schema=public
      JWT_SECRET: sua_chave_secreta_super_segura_aqui_mude_em_producao
      JWT_EXPIRES_IN: 7d
      PORT: 8080
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
